<a href="https://colab.research.google.com/github/SandhuruT/Data_Science_01/blob/main/Data_Science_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

messy_dt = pd.read_csv('/content/messy_sales.csv')
messy_dt.head()

,order_id,customer_name,age,city,product_category,quantity,unit_price,discount,payment_method,order_date,delivery_days,rating,returned
0,1001,Raj Kumar,28.0,Mumbai,Electronics,2,1500,10.0,UPI,2023-01-05,3.0,4.0,No
1,1002,Priya Sharma,NaN,Delhi,Clothing,1,800,NaN,Credit Card,2023-01-07,5.0,3.0,No
2,1003,Amit Singh,35.0,Bangalore,Electronics,3,2000,15.0,UPI,2023-01-10,NaN,5.0,No
3,1004,Raj Kumar,28.0,Mumbai,Electronics,2,1500,10.0,UPI,2023-01-05,3.0,4.0,No
4,1005,Sneha Patel,999.0,Chennai,Books,2,500,0.0,Debit Card,2023-01-12,4.0,2.0,Yes

In [4]:
messy_dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50 non-null     int64
 1   customer_name     49 non-null     object
 2   age               48 non-null     float64
 3   city              50 non-null     object
 4   product_category  50 non-null     object
 5   quantity          50 non-null     int64
 6   unit_price        50 non-null     int64
 7   discount          48 non-null     float64
 8   payment_method    50 non-null     object
 9   order_date        50 non-null     object
 10  delivery_days     46 non-null     float64
 11  rating            48 non-null     float64
 12  returned          50 non-null     object
dtypes: float64(4), int64(3), object(6)
memory usage: 5.2+ KB

In [8]:
messy_dt.isnull().sum()

order_id            0
customer_name       1
age                 2
city                0
product_category    0
quantity            0
unit_price          0
discount            2
payment_method      0
order_date          0
delivery_days       4
rating              2
returned            0
dtype: int64

In [9]:
messy_dt.dtypes

order_id              int64
customer_name        object
age                 float64
city                 object
product_category     object
quantity              int64
unit_price            int64
discount            float64
payment_method       object
order_date           object
delivery_days       float64
rating              float64
returned             object
dtype: object

In [7]:
messy_dt.describe()

,order_id,age,quantity,unit_price,discount,delivery_days,rating
count,50.00000,48.000000,50.000000,50.000000,48.000000,46.000000,48.000000
mean,1025.50000,53.375000,1.760000,2938.160000,6.354167,4.195652,3.833333
std,14.57738,139.737691,0.959592,4080.020515,5.901639,1.654886,0.833688
min,1001.00000,-5.000000,0.000000,499.000000,0.000000,2.000000,2.000000
25%,1013.25000,28.000000,1.000000,750.000000,0.000000,3.000000,3.000000
50%,1025.50000,32.500000,1.500000,1050.000000,7.500000,4.000000,4.000000
75%,1037.75000,39.000000,2.000000,2200.000000,10.000000,5.000000,4.000000
max,1050.00000,999.000000,4.000000,15999.000000,20.000000,8.000000,5.000000