<a href="https://colab.research.google.com/github/SandhuruT/Data_Science_01/blob/main/Data_Science_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_hr = pd.read_csv('/content/hr_attrition.csv')
df_hr.head()

,employee_id,age,gender,department,job_role,education,years_at_company,years_in_role,monthly_income,percent_salary_hike,job_satisfaction,work_life_balance,overtime,distance_from_home,num_companies_worked,training_times_last_year,attrition
0,E001,41,Male,Sales,Sales Executive,Bachelor,6,4,5993,11,3,1,Yes,1,8,0,Yes
1,E002,49,Female,Research,Research Scientist,Master,10,7,5130,23,2,3,No,8,1,3,No
2,E003,37,Male,Research,Lab Technician,Bachelor,0,0,2090,15,3,3,Yes,2,6,3,Yes
3,E004,33,Female,Research,Research Scientist,Master,8,7,2909,11,3,3,Yes,3,1,2,No
4,E005,27,Male,Research,Lab Technician,Bachelor,2,2,3468,12,2,3,No,2,9,2,No

In [4]:
df_hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               200 non-null    object
 1   age                       200 non-null    int64
 2   gender                    200 non-null    object
 3   department                200 non-null    object
 4   job_role                  200 non-null    object
 5   education                 200 non-null    object
 6   years_at_company          200 non-null    int64
 7   years_in_role             200 non-null    int64
 8   monthly_income            200 non-null    object
 9   percent_salary_hike       200 non-null    int64
 10  job_satisfaction          200 non-null    int64
 11  work_life_balance         200 non-null    int64
 12  overtime                  200 non-null    object
 13  distance_from_home        200 non-null    int64
 14  num_companies_worked      200 non-null    int64
 15  training_times_last_year  200 non-null    int64
 16  attrition                 200 non-null    object
dtypes: int64(9), object(8)
memory usage: 26.7+ KB

In [5]:
df_hr.describe()

,age,years_at_company,years_in_role,percent_salary_hike,job_satisfaction,work_life_balance,distance_from_home,num_companies_worked,training_times_last_year
count,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,38.405000,9.330000,8.520000,13.56500,2.835000,2.540000,10.320000,3.065000,2.290000
std,8.377463,6.065066,5.892641,3.55089,0.837425,0.663779,8.255201,2.575645,1.005462
min,18.000000,0.000000,0.000000,11.00000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,32.000000,5.000000,4.000000,11.00000,2.000000,2.000000,3.000000,1.000000,2.000000
50%,38.000000,9.000000,8.000000,13.00000,3.000000,3.000000,9.000000,3.000000,2.000000
75%,44.000000,14.000000,13.000000,14.00000,3.000000,3.000000,16.250000,4.000000,3.000000
max,59.000000,25.000000,24.000000,30.00000,4.000000,3.000000,29.000000,15.000000,5.000000

In [6]:
df_is_null = df_hr.isnull().sum()
df_is_null

employee_id                 0
age                         0
gender                      0
department                  0
job_role                    0
education                   0
years_at_company            0
years_in_role               0
monthly_income              0
percent_salary_hike         0
job_satisfaction            0
work_life_balance           0
overtime                    0
distance_from_home          0
num_companies_worked        0
training_times_last_year    0
attrition                   0
dtype: int64

In [7]:
df_hr.duplicated().sum()

np.int64(0)

In [9]:
df_hr.dtypes

employee_id                 object
age                          int64
gender                      object
department                  object
job_role                    object
education                   object
years_at_company             int64
years_in_role                int64
monthly_income              object
percent_salary_hike          int64
job_satisfaction             int64
work_life_balance            int64
overtime                    object
distance_from_home           int64
num_companies_worked         int64
training_times_last_year     int64
attrition                   object
dtype: object